### ISSUE TITLE
Contribute to django-treenode ?

### ISSUE THREAD

**Issue by jacobjove** [TimurKady/django-fast-treenode#4]
Perhaps this should be contributed to django-treenode rather than maintained as a separate package?

@TimurKady

**Comment by iacobfred** [comment]
Looks like the author of django-treenode would be happy to review and accept these changes if they are contributed as a PR. @TimurKady , since you made these improvements (nice work by the way!), I think you are the best equipped to make the contribution, but I could give it a go if you are not interested.

**Comment by TimurKady** [comment]
This question should be addressed to Fabio. I suggested this from the very beginning

**Comment by iacobfred** [comment]
https://github.com/fabiocaccamo/django-treenode/issues/130#issuecomment-1854192642
